# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_host_id", models.IntegerField(verbose_name="host id")),
                ("bk_file_dir", models.CharField(max_length=1024, verbose_name="file directory")),
                ("bk_file_suffix", models.CharField(max_length=255, verbose_name="file suffix")),
                ("bk_backup_name", models.CharField(max_length=1024, verbose_name="backup file name")),
                ("bk_file_create_time", models.CharField(max_length=30, verbose_name="backup time")),
                ("bk_file_operator", models.CharField(max_length=30, verbose_name="backup operator")),
                ("bk_job_link", models.CharField(max_length=255, verbose_name="JOB result link")),
            ],
            options={
                "verbose_name": "backup record",
                "verbose_name_plural": "backup records",
            },
        ),
    ]
